print('hello world')
print('#hello again')
print('I like typing this')
print('This is fun')
print('Yay! Printing')
print("I'd much rather you 'not'")
print('I "said" do not touch this')
print('I am learning python')
print('I am learning python')
print('I am learning python')
print('I am learning python')